// <auto-generated />
namespace EventCloud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpgradeTo_ModuleZero_0_7_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpgradeTo_ModuleZero_0_7_4));
        
        string IMigrationMetadata.Id
        {
            get { return "201512031853476_UpgradeTo_ModuleZero_0_7_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
