// <auto-generated />
namespace EventCloud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adde_Event_MaxRegistrationCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adde_Event_MaxRegistrationCount));
        
        string IMigrationMetadata.Id
        {
            get { return "201510191355136_Adde_Event_MaxRegistrationCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
