// <auto-generated />
namespace EventCloud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Upgraded_To_Abp_v0_10_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Upgraded_To_Abp_v0_10_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201607190808209_Upgraded_To_Abp_v0_10_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
